/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package learn;

import learn.com.test.demo.dao.AppInfoRepository;
import learn.com.test.demo.entity.AppInfo;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import java.util.List;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test")
class AppTest {

    public static void main(String[] args) {
        SpringApplication.run(AppTest.class, args);
    }

    @Autowired
    private AppInfoRepository appInfoRepository;

    @Test
    void exampleTest() {
        // ...
        AppInfo appInfo = new AppInfo();
        appInfo.setAppName("app");
        appInfo.setAppDescription("this a test app demo");
        appInfoRepository.save(appInfo);
    }

    @Test
    void testFindAll() {
        List<AppInfo> userList = appInfoRepository.findAll();
        userList.forEach(user -> System.out.println(user.getAppName()+":"+user.getAppDescription()));
    }
}
